### ISSUE TITLE
Unable to find version 'latest'

### ISSUE THREAD

**Issue by ataylormays-duetto** [dwardu89/aws-ssm-parameter-store#24]
**Describe the bug**
When using the GH action w/ the following configuration, GH gives the error message 

```
Getting action download info
Error: Unable to resolve action `dwardu89/aws-ssm-parameter-store@latest`, unable to find version `latest`.
```

**To Reproduce**
Configuration:

```
      - name: Add version to SSM parameter store
        uses: dwardu89/aws-ssm-parameter-store@latest
        with:
          ssm-path: ${{ inputs.DEPLOYMENT_VERSION_SSM_PATH }}
          ssm-value: ${{ env.PROJECT_VERSION }}
          aws-region: us-west-2
          ssm-value-type: "String"
          ssm-value-overwrite: true
```

**Expected behavior**
The SSM path is updated with the provided value

**Screenshots**
<img width="1416" alt="image" src="https://user-images.githubusercontent.com/38015884/211940828-208adaba-efd7-4e1b-8925-2a17c9690ebc.png">

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
